### ISSUE TITLE
[Question] Is that your package on PyPI?

### ISSUE THREAD

**Issue by Martin15135215** [WISDEM/pyFrame3DD#7] opened 2023-10-06 12:42 UTC
I saw in PyPI the library named "pyframe3dd" → https://pypi.org/project/pyframe3dd/

Is that from this repo? If not, would you publish pyFrame3DD on PyPI?

**Comment by gbarter** [comment] 2023-10-06 13:10
Interesting!  It looks like that PyPI package comes from: https://github.com/Saul11235/py_frame3dd

Somebody else also wanted a python interface to Frame3DD, although their approach is a bit more lightweight.

Not sure about putting our pyframe3dd up on PyPI now as a standalone.  Not sure how to keep the two separate.

**Comment by Martin15135215** [comment] 2023-10-06 14:42
I thought it is possible to have a PyPI name that is separate from the module name

So in PyPI there would be something like `pip install wisdem-pyframe3dd` to install the packages in a python env

And in the python env it would be possible to do `import pyframe3dd`

However, someone should not install both packages in the same python env

**Comment by gbarter** [comment] 2023-10-06 15:47
Thanks for the tip.  I will put it on the to-do list, but might not get to it for a little bit.

**Comment by gbarter** [comment] 2023-10-09 14:15
Looks like this may be done!
https://pypi.org/project/WISDEM-pyFrame3DD/

Thanks for the encouragement

**Comment by Martin15135215** [comment] 2023-10-09 14:27
Awesome!

Some quick question:

Here is:
https://github.com/WISDEM/pyFrame3DD/blob/6c40bd82fcf23bb46650eb8a7aee1af34f9008f2/pyproject.toml#L11
However, here is:
https://github.com/WISDEM/pyFrame3DD/blob/6c40bd82fcf23bb46650eb8a7aee1af34f9008f2/README.md?plain=1#L34

Which licence is it? A bit confusing to look at https://pypi.org/project/WISDEM-pyFrame3DD/

![Screenshot_20231009_162506](https://github.com/WISDEM/pyFrame3DD/assets/110968398/88fd774d-2168-4023-bf9c-5b23435298b6)



And:

https://github.com/WISDEM/pyFrame3DD/blob/6c40bd82fcf23bb46650eb8a7aee1af34f9008f2/pyproject.toml#L24

Is it not stable?

**Comment by gbarter** [comment] 2023-10-09 19:01
Thanks for catching the license copy-paste error.  I have pushed a fix.  The license for this repository should be GPL v3 since that is the Frame3DD license and GPLv3 is "viral" or copy-left.  The Frame3DD lead has given NREL special dispensation to use Frame3DD within a code released under Apache for renewable energy applications, which is how WISDEM retains its license.

As for the Beta status, this code is stable as much as research software is stable.  There is no extensive suite of unit tests or regression tests and there are no guarantees of accuracy beyond what the Frame3DD homepage describes.  To me, that is a perpetual beta status, but others might label that as stable.

**Comment by Martin15135215** [comment] 2023-10-09 19:20
Thanks for the clarification! I think you still need to push a new version on PyPI, so that the meta information can change.

**Comment by Martin15135215** [comment] 2023-10-23 19:22
I am not sure if that was intended. However, I need to write `import pyframe3dd` instead of `import frame3dd`

See https://github.com/WISDEM/pyFrame3DD/blob/17d167f347ea7c7f881253f74fd45c547e95be84/examples/exB.py#L12

**Comment by gbarter** [comment] 2023-10-24 02:54
Corrected- thank you!

**Comment by Martin15135215** [comment] 2023-11-01 17:13
![image](https://github.com/WISDEM/pyFrame3DD/assets/110968398/5e30d990-1686-4408-9739-5aebe61f1828)

I would like to mention that there is still some licence mismatch

Afterwards, we can close this issue, since the beginning question of mine is already solved :)

**Comment by gbarter** [comment] 2023-11-01 19:58
Thanks, I think I finally caught the last driver of the discrepancy

**Closed** 2023-11-08 13:46 UTC
